license_db/urls.py
from django.urls import path

from . import views

app_name = 'license_db'

urlpatterns = [
    path('', views.view, name='view'),
    path('auth/', views.auth, name='auth'),
    path('auth/<str:action>/', views.auth, name='auth'),
    path('import/', views.import_data, name='import_data'),
    path('import/preview/', views.preview_import, name='preview_import'),
    path('import/submit/', views.submit_import, name='submit_import'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('license_db.urls')),
    path('admin/', admin.site.urls),
]

license_db/models.py
from datetime import date

from django.db import models

from license_db.utils import year_after


class License(models.Model):
    name = models.CharField('name', max_length=200)
    category = models.ForeignKey(
        'LicenseCategory',
        on_delete=models.CASCADE,
    )
    location = models.ForeignKey(
        'LicenseLocation',
        on_delete=models.CASCADE,
    )
    type = models.ForeignKey(
        'LicenseType',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    quantity = models.PositiveIntegerField('quantity', default=0)
    expires = models.DateField('expires', default=year_after())
    comment = models.CharField('comment', max_length=200, blank=True)
    created = models.DateTimeField('created', auto_now_add=True)
    modified = models.DateTimeField('modified', auto_now=True)

    def __str__(self):
        return self.name

    @classmethod
    def _generate(cls, number: int) -> None:
        from random import randint, choice
        from mimesis import Business, Text

        business = Business()
        text = Text()

        lic_categories = (
            'software',
            'hardware',
        )

        for lic_category in lic_categories:
            LicenseCategory.objects.create(
                name=lic_category,
            )

        lic_locations = (
            'store',
            'central office',
            'data center',
        )

        for lic_location in lic_locations:
            LicenseLocation.objects.create(
                name=lic_location,
            )

        for _ in range(number):
            License.objects.create(
                name=business.company(),
                category=choice(LicenseCategory.objects.all()),
                location=choice(LicenseLocation.objects.all()),
                quantity=randint(0, 10000),
                comment=text.quote(),
            )

        return None


class LicenseCategory(models.Model):
    name = models.CharField('category', max_length=200, unique=True)

    def __str__(self):
        return self.name


class LicenseLocation(models.Model):
    name = models.CharField('location', max_length=200, unique=True)

    def __str__(self):
        return self.name


class LicenseType(models.Model):
    name = models.CharField('type', max_length=200, unique=True)

    def __str__(self):
        return self.name


class ImportLicense(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    quantity = models.PositiveIntegerField(default=0)
    expires = models.DateField(default=year_after())
    comment = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class ExcelEntry:
    def __init__(
            self,
            name: str,
            category: str,
            location: str,
            expires: date=year_after(),
            lic_type: str='',
            quantity: int=0,
            comment: str='',
            exists: bool=False,
    ):
        self.name = name
        self.category = category
        self.location = location
        self.expires = expires
        self.type = lic_type
        self.quantity = quantity
        self.comment = comment
        self.exists = exists

    def __str__(self):
        return self.name

license_db/forms.py
from django import forms


class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()

license_db/views.py
from typing import List

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from decouple import config
from openpyxl import load_workbook

from license_db.handlers import save_to_disk
from license_db.utils import excel_columns, prepare_cell_value
from .models import License, ExcelEntry, LicenseCategory, LicenseLocation, LicenseType, ImportLicense
from .forms import UploadFileForm


def auth(request, action='login'):
    if action == 'logout':
        logout(request)
        return redirect('license_db:auth')

    context = {
        'logo': config('LOGO', default='My Logo'),
        'site_title': config('SITE_TITLE', default='My Site'),
        'login': {
            'prefix': config('LOGIN_PREFIX', default='DOMAIN\\'),
            'placeholder': config('LOGIN_PLACEHOLDER', default='Login'),
        },
        'access_denied': False,
    }

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request=request,
            username=username,
            password=password,
        )

        if user is not None and user.is_staff:
            login(request, user)
            return redirect('license_db:view')
        else:
            context['access_denied'] = True

    return render(request, 'license_db/auth.html', context)


def view(request):
    if request.user.is_anonymous:
        return redirect('license_db:auth')

    context = {
        'logo': config('LOGO', default='My Logo'),
        'site_title': config('SITE_TITLE', default='My Site'),
    }

    lic_tree = {}
    for lic in License.objects.all():
        if lic.category.name not in lic_tree.keys():
            lic_tree[lic.category.name] = {}

        if lic.location.name not in lic_tree[lic.category.name].keys():
            lic_tree[lic.category.name][lic.location.name] = []

        lic_tree[lic.category.name][lic.location.name].append(lic)

    context['lic_tree'] = lic_tree

    return render(request, 'license_db/view.html', context)


def parse_excel(file_path: str) -> None:
    ImportLicense.objects.all().delete()

    wb = load_workbook(file_path)
    ws = wb.active

    rows = ws.rows
    next(rows)  # skip header row

    for row in rows:
        if not prepare_cell_value(row, 'name'):
            break

        ImportLicense.objects.create(
            name=prepare_cell_value(row, 'name'),
            category=prepare_cell_value(row, 'category'),
            location=prepare_cell_value(row, 'location'),
            type=prepare_cell_value(row, 'lic_type'),
            quantity=prepare_cell_value(row, 'quantity'),
            expires=prepare_cell_value(row, 'expires'),
            comment=prepare_cell_value(row, 'comment'),
        )

    return None


def preview_import(request):
    saved_file_info = request.session['saved_file_info']
    parse_excel(saved_file_info['path'])

    lic_tree = {}
    for lic in ImportLicense.objects.all():
        if lic.category not in lic_tree.keys():
            lic_tree[lic.category] = {}

        if lic.location not in lic_tree[lic.category].keys():
            lic_tree[lic.category][lic.location] = []

        lic_tree[lic.category][lic.location].append(lic)

    context = {
        'logo': config('LOGO', default='My Logo'),
        'site_title': config('SITE_TITLE', default='My Site'),
        'lic_tree': lic_tree,
        'import_file_name': saved_file_info['name'],
    }

    return render(request, 'license_db/import.html', context)


def submit_import(request) -> redirect:
    for entry in ImportLicense.objects.all():
        existing_category = LicenseCategory.objects.filter(
            name=entry.category.lower()
        ).first()

        if existing_category:
            category = existing_category
        else:
            category = LicenseCategory(name=entry.category.lower())
            category.save()

        existing_location = LicenseLocation.objects.filter(
            name=entry.location.lower()
        ).first()

        if existing_location:
            location = existing_location
        else:
            location = LicenseLocation(name=entry.location.lower())
            location.save()

        existing_type = LicenseType.objects.filter(
            name=entry.type
        ).first()

        if existing_type:
            lic_type = existing_type
        else:
            lic_type = LicenseType(name=entry.type)
            lic_type.save()

        if not License.objects.filter(
            name=entry.name,
            category=category,
            location=location,
            type=lic_type,
            quantity=entry.quantity,
            expires=entry.expires,
            comment=entry.comment,
        ).exists():
            License.objects.create(
                name=entry.name,
                category=category,
                location=location,
                type=lic_type,
                quantity=entry.quantity,
                expires=entry.expires,
                comment=entry.comment,
            )

    return redirect('license_db:view')


def import_data(request):
    if request.user.is_anonymous:
        return redirect('license_db:auth')

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)

        preview_pressed = bool(request.POST.get('preview'))
        submit_pressed = bool(request.POST.get('import'))

        if preview_pressed and form.is_valid():
            saved_file_info = save_to_disk(request.FILES['file'])
            request.session['saved_file_info'] = saved_file_info

            return redirect('license_db:preview_import')
        elif submit_pressed:
            return redirect('license_db:submit_import')
    else:
        form = UploadFileForm()

    context = {
        'logo': config('LOGO', default='My Logo'),
        'site_title': config('SITE_TITLE', default='My Site'),
        'form': form,
    }

    return render(request, 'license_db/import.html', context)

license_db/templates/license_db/auth.html
{% extends 'license_db/index.html' %}

{% block main %}
  <div class="login-group-wrapper">
    <form class="login-group" name="login-group" method="post">
      {% if access_denied %}
      <div id="login-error" class="alert alert-danger" role="alert">
        Ouch! Access denied!
      </div>
      {% endif %}
      {% csrf_token %}
      <div id="login-login" class="input-group">
        <div class="input-group-prepend">
          <span id="domain-prepend"
                class="input-group-text">{{ login.prefix }}
          </span>
        </div>
        <input name="username" type="text"
               class="form-control" placeholder="{{ login.placeholder }}" />
      </div>
      <div id="login-password" class="input-group">
        <input name="password" type="password"
               class="form-control" placeholder="Password" />
      </div>
      <button id="login-submit" type="submit"
              class="btn">Login</button>
    </form>
  </div>

{% endblock %}

license_db/templates/license_db/import.html
{% extends "license_db/index.html" %}

{% load static %}
{% load name_to_tag_part %}
{% block main %}
  <div class="import-control-row">
    <div class="input-group control-search-group" id="import-search">
      <div class="input-group-prepend">
        <span class="input-group-text control-prepend-icon">
          <img src="{% static "license_db/img/search.svg" %}">
        </span>
      </div>
      <input id="search-area" type="search"
             class="form-control" placeholder="type to search">
    </div>

    <div class="input-group control-collapse-group" id="import-collapse">
      <div class="btn-group">
        <span id="expand-all" class="btn control-button" title="Expand all">
          <img src="{% static "license_db/img/chevrons-down.svg" %}">
        </span>
        <span id="collapse-all" class="btn control-button" title="Collapse all">
          <img src="{% static "license_db/img/chevrons-up.svg" %}">
        </span>
      </div>
    </div>

    <form enctype="multipart/form-data" method="post"
          action="{% url 'license_db:import_data' %}" id="import-form">
      {% csrf_token %}
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text control-prepend-icon">
            <img src="{% static "license_db/img/file.svg" %}">
          </span>
        </div>
        <div class="custom-file">
          <input type="file" class="custom-file-input control-button"
                 id="file-upload-input" name="file">
          <label class="custom-file-label" id="file-upload-label"
                 for="file-upload-input">
            {% if import_file_name %}
              {{ import_file_name }}
            {% else %}
              choose file
            {% endif %}

          </label>
        </div>
      </div>

      <span class="btn-group control-preview-import-group">
        <button name="preview" value="preview"
                type="submit" class="btn control-button">Preview</button>
        <button name="import" value="submit"
                type="submit" class="btn control-button">Import</button>
      </span>
      <div class="btn-group">
          <button name="reset" value="reset"
                  type="submit" class="btn control-button">Reset</button>
      </div>
    </form>
  </div>

  {% if lic_tree %}
    <div class="view-page-container">
      {% for category, locations in lic_tree.items %}
        <button class="lic-category-button collapse-button btn"
                type="button" data-toggle="collapse"
                data-target="#view-{{ category | name_to_tag_part }}-container">
          {{ category | capfirst }}
        </button>

        <div id="view-{{ category | name_to_tag_part }}-container"
             class="view-category-container collapse">

          {% for location, licenses in locations.items %}
            <button class="lic-location-button collapse-button btn"
                    type="button" data-toggle="collapse"
                    data-target="#view-{{ category | name_to_tag_part }}-{{ location | name_to_tag_part }}-container">
              {{ location | capfirst }}
            </button>

            <div id="view-{{ category | name_to_tag_part }}-{{ location | name_to_tag_part }}-container"
                 class="license-group collapse">
              <div class="lic-group-header-row">
                <span class="lic-group-header-item">Name</span>
                <span class="lic-group-header-item">Type</span>
                <span class="lic-group-header-item">Quantity</span>
                <span class="lic-group-header-item">Expires</span>
                <span class="lic-group-header-item">Comment</span>
              </div>

              {% for license in licenses %}
                <div class="lic-group-item">
                  <span class="lic-name">{{ license.name }}</span>
                  <span class="lic-type">{{ license.type | default_if_none:'-' }}</span>
                  <span class="lic-quantity">{{ license.quantity }}</span>
                  <span class="lic-expires">{{ license.expires | date:'d.m.Y' }}</span>
                  <span class="lic-comment">{{ license.comment | default:'-' }}

                  </span>
                </div>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

license_db/templates/license_db/index.html
{% load static %}<!DOCTYPE html>
<html lang="en" xmlns:https="http://www.w3.org/1999/xhtml">
<head>
  <link rel="stylesheet" href="{% static 'license_db/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static "license_db/css/style.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:700" rel="stylesheet">
  <title>{% block title %}{{ site_title }}{% endblock %}</title>
</head>

<body>
  <header>
    {% block header %}
      <div class="logo"><h5>{{ logo }}</h5></div>
      <div class="title"></div>
      <div class="user">
      {% if request.user.is_authenticated %}
        <span>
          <a href="{% url 'license_db:view' %}" title="View">
            <img class="header-button" id="button-view"
                 src="{% static 'license_db/img/view.svg' %}">
          </a>
        </span>
        <span>
          <a href="{% url 'license_db:import_data' %}" title="Import">
            <img class="header-button" id="button-import"
                 src="{% static 'license_db/img/import.svg' %}">
          </a>
        </span>
        <span>
          <a href="{% url 'admin:index' %}" title="Edit">
            <img class="header-button" id="button-edit"
                 src="{% static 'license_db/img/edit.svg' %}">
          </a>
        </span>
        <span id="user-full-name">{{ request.user.get_full_name }}</span>
        <span>
          <a href="{% url 'license_db:auth' action='logout' %}"
             title="Logout">
            <img class="header-button" id="button-logout"
                 src="{% static 'license_db/img/log-out.svg' %}">
          </a>
        </span>
      {% endif %}
      </div>
    {% endblock %}
  </header>

  <main>
    {% block main %}{% endblock %}
{#    {% block content %}{% endblock %}#}
  </main>

  <script src="{% static "license_db/js/jquery-3.3.1.min.js" %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="{% static "license_db/js/bootstrap.min.js" %}"></script>
  <script src="{% static "license_db/js/main.js" %}"></script>
</body>
</html>

license_db/templates/license_db/main.html
{% extends "license_db/index.html" %}

{% load static %}
{% load name_to_tag_part %}
{% block content %}
  <div class="control-row">
    <div class="input-group control-search-group">
      <div class="input-group-prepend">
        <span class="input-group-text">
          <img src="{% static "license_db/img/search.svg" %}">
        </span>
      </div>
      <input id="search-area" type="search"
             class="form-control" placeholder="type to search">
    </div>

    <div class="input-group control-collapse-group">
      <div class="input-group-prepend">
        <span id="expand-all" class="input-group-text" title="Expand all">
          <img src="{% static "license_db/img/chevrons-down.svg" %}">
        </span>
        <span id="collapse-all" class="input-group-text" title="Collapse all">
          <img src="{% static "license_db/img/chevrons-up.svg" %}">
        </span>
      </div>
    </div>
  </div>

  {% if lic_tree %}
    <div class="view-page-container">
      {% for category, locations in lic_tree.items %}
        <button class="lic-category-button collapse-button btn"
                type="button" data-toggle="collapse"
                data-target="#view-{{ category | name_to_tag_part }}-container">
          {{ category | capfirst }}
        </button>

        <div id="view-{{ category | name_to_tag_part }}-container"
             class="view-category-container collapse">

          {% for location, licenses in locations.items %}
            <button class="lic-location-button collapse-button btn"
                    type="button" data-toggle="collapse"
                    data-target="#view-{{ category | name_to_tag_part }}-{{ location | name_to_tag_part }}-container">
              {{ location | capfirst }}
            </button>

            <div id="view-{{ category | name_to_tag_part }}-{{ location | name_to_tag_part }}-container"
                 class="license-group collapse">
              <div class="lic-group-header-row">
                <span class="lic-group-header-item">Name</span>
                <span class="lic-group-header-item">Type</span>
                <span class="lic-group-header-item">Quantity</span>
                <span class="lic-group-header-item">Expires</span>
                <span class="lic-group-header-item">Comment</span>
              </div>

              {% for license in licenses %}
                <div class="lic-group-item">
                  <span class="lic-name">{{ license.name }}</span>
                  <span class="lic-type">{{ license.type | default_if_none:'-' }}</span>
                  <span class="lic-quantity">{{ license.quantity }}</span>
                  <span class="lic-expires">{{ license.expires | date:'d.m.Y' }}</span>
                  <span class="lic-comment">{{ license.comment | default:'-' }}</span>
                </div>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

license_db/templates/license_db/view.html
{% extends "license_db/index.html" %}

{% load static %}
{% load name_to_tag_part %}
{% block main %}
  <div class="control-row">
    <div class="input-group control-search-group">
      <div class="input-group-prepend">
        <span class="input-group-text">
          <img src="{% static "license_db/img/search.svg" %}">
        </span>
      </div>
      <input id="search-area" type="search"
             class="form-control" placeholder="type to search">
    </div>

    <div class="input-group control-collapse-group">
      <div class="input-group-prepend">
        <span id="expand-all" class="input-group-text" title="Expand all">
          <img src="{% static "license_db/img/chevrons-down.svg" %}">
        </span>
        <span id="collapse-all" class="input-group-text" title="Collapse all">
          <img src="{% static "license_db/img/chevrons-up.svg" %}">
        </span>
      </div>
    </div>
  </div>

  {% if lic_tree %}
    <div class="view-page-container">
      {% for category, locations in lic_tree.items %}
        <button class="lic-category-button collapse-button btn"
                type="button" data-toggle="collapse"
                data-target="#view-{{ category | name_to_tag_part }}-container">
          {{ category | capfirst }}
        </button>

        <div id="view-{{ category | name_to_tag_part }}-container"
             class="view-category-container collapse">

          {% for location, licenses in locations.items %}
            <button class="lic-location-button collapse-button btn"
                    type="button" data-toggle="collapse"
                    data-target="#view-{{ category | name_to_tag_part }}-{{ location | name_to_tag_part }}-container">
              {{ location | capfirst }}
            </button>

            <div id="view-{{ category | name_to_tag_part }}-{{ location | name_to_tag_part }}-container"
                 class="license-group collapse">
              <div class="lic-group-header-row">
                <span class="lic-group-header-item">Name</span>
                <span class="lic-group-header-item">Type</span>
                <span class="lic-group-header-item">Quantity</span>
                <span class="lic-group-header-item">Expires</span>
                <span class="lic-group-header-item">Comment</span>
              </div>

              {% for license in licenses %}
                <div class="lic-group-item">
                  <span class="lic-name">{{ license.name }}</span>
                  <span class="lic-type">{{ license.type | default_if_none:'-' }}</span>
                  <span class="lic-quantity">{{ license.quantity }}</span>
                  <span class="lic-expires">{{ license.expires | date:'d.m.Y' }}</span>
                  <span class="lic-comment">{{ license.comment | default:'-' }}</span>
                </div>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}